import {generatePDF} from 'react-native-html-to-pdf';
import Share from 'react-native-share';
import {Platform, Alert} from 'react-native';

// ── Shared helpers ──

function escapeHTML(str: string): string {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function capitalize(str: string): string {
  return str ? str.charAt(0).toUpperCase() + str.slice(1).toLowerCase() : '';
}

function formatPrice(v: number): string {
  if (v == null) return '';
  return Number(v).toLocaleString('en-US', {minimumFractionDigits: 2, maximumFractionDigits: 2});
}

const BASE_STYLES = `
  @page { size: A4; margin: 16mm; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    color: #1a1a2e;
    background: #ffffff;
    font-size: 14px;
    line-height: 1.5;
  }
  .header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-bottom: 16px;
    border-bottom: 2px solid #0ea5e9;
    margin-bottom: 20px;
  }
  .brand {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .brand-name {
    font-size: 20px;
    font-weight: 800;
    color: #0ea5e9;
  }
  .brand-sub {
    font-size: 11px;
    color: #94a3b8;
    font-weight: 500;
  }
  .section-title {
    font-size: 13px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #64748b;
    margin-bottom: 10px;
    margin-top: 24px;
  }
  .disclaimer {
    background: #fef9c3;
    border: 1px solid #fde68a;
    border-radius: 10px;
    padding: 14px 16px;
    margin-top: 24px;
  }
  .disclaimer-title {
    font-size: 12px;
    font-weight: 700;
    color: #92400e;
    margin-bottom: 4px;
  }
  .disclaimer-text {
    font-size: 11px;
    color: #78350f;
    line-height: 1.6;
  }
  .footer {
    text-align: center;
    margin-top: 24px;
    padding-top: 14px;
    border-top: 1px solid #e5e7eb;
    font-size: 10px;
    color: #94a3b8;
  }
  .bullet-item {
    font-size: 12px;
    color: #1e3a5f;
    line-height: 1.6;
    padding-left: 14px;
    position: relative;
    margin-bottom: 4px;
  }
  .bullet-item::before {
    content: "\\2022";
    position: absolute;
    left: 0;
    color: #0ea5e9;
    font-weight: 700;
  }
  .card {
    background: #f8fafc;
    border: 1px solid #e5e7eb;
    border-radius: 10px;
    padding: 14px;
    margin-bottom: 10px;
  }
  .card h5 {
    font-size: 12px;
    font-weight: 700;
    color: #64748b;
    margin-bottom: 8px;
  }
  .bar-container {
    height: 6px;
    background: #e5e7eb;
    border-radius: 3px;
    overflow: hidden;
    margin-top: 4px;
  }
  .bar-fill {
    height: 100%;
    border-radius: 3px;
  }
`;

const HEADER_HTML = `
  <div class="header">
    <div class="brand">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42 42" width="42" height="42">
        <rect width="42" height="42" rx="10" fill="#F16439"/>
        <circle cx="29" cy="29" r="17" fill="#39C9DF"/>
        <text x="21" y="28" text-anchor="middle" font-size="17" font-weight="900" fill="#FFFFFF" font-family="-apple-system, Arial, Helvetica, sans-serif" letter-spacing="-0.5">RC</text>
      </svg>
      <div>
        <div class="brand-name">RapidCapsule</div>
`;

function buildHeader(subtitle: string): string {
  return `${HEADER_HTML}<div class="brand-sub">${escapeHTML(subtitle)}</div></div></div></div>`;
}

function buildDisclaimer(text: string): string {
  return `
    <div class="disclaimer">
      <div class="disclaimer-title">Important Disclaimer</div>
      <div class="disclaimer-text">${escapeHTML(text)}</div>
    </div>`;
}

function buildFooter(): string {
  const date = new Date().toLocaleDateString('en-US', {month: 'long', day: 'numeric', year: 'numeric'});
  return `<div class="footer">Generated by RapidCapsule &bull; rapidcapsule.com &bull; ${date}</div>`;
}

async function generateAndShare(html: string, fileName: string): Promise<void> {
  try {
    const file = await generatePDF({
      html,
      fileName,
      directory: Platform.OS === 'ios' ? 'Documents' : 'Downloads',
      base64: false,
    });

    if (!file.filePath) {
      throw new Error('PDF generation failed');
    }

    await Share.open({
      url: Platform.OS === 'ios' ? file.filePath : `file://${file.filePath}`,
      type: 'application/pdf',
      title: fileName.replace(/_/g, ' '),
      subject: fileName.replace(/_/g, ' '),
    });
  } catch (error: any) {
    if (
      error?.message?.includes?.('User did not share') ||
      error?.message?.includes?.('cancelled') ||
      error?.message?.includes?.('dismiss')
    ) {
      return;
    }
    Alert.alert('PDF Error', 'Could not generate the report. Please try again.');
  }
}

// ═══════════════════════════════════════════════════════
// Drug Interaction Report PDF
// ═══════════════════════════════════════════════════════

export async function generateDrugInteractionPDF(data: any): Promise<void> {
  const drugsChecked = data?.drugs_checked || [];
  const interactions = data?.interactions || data?.results || [];
  const summary = data?.summary || '';

  const severityColor = (s: string) => {
    if (s === 'major' || s === 'contraindicated') return '#ef4444';
    if (s === 'moderate') return '#f59e0b';
    return '#3b82f6';
  };

  const drugsHTML = drugsChecked.map((d: string) => `<span style="display:inline-block;background:#f1f5f9;border-radius:6px;padding:3px 10px;margin:2px 4px;font-size:12px;font-weight:600;">${escapeHTML(d)}</span>`).join('');

  let interactionsHTML = '';
  if (interactions.length === 0) {
    interactionsHTML = `<div style="text-align:center;padding:20px;color:#10b981;font-weight:600;">No significant interactions found.</div>`;
  } else {
    for (const ix of interactions) {
      const sColor = severityColor(ix.severity);
      interactionsHTML += `
        <div style="margin-bottom:16px;">
          <div style="background:${sColor};color:#fff;padding:8px 12px;border-radius:8px 8px 0 0;font-weight:700;font-size:12px;text-transform:uppercase;">
            ${escapeHTML(ix.severity)} &mdash; ${escapeHTML(ix.drug1 || ix.drugs?.[0] || '')} + ${escapeHTML(ix.drug2 || ix.drugs?.[1] || '')}
          </div>
          <div style="border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px;padding:12px;">
            ${ix.description ? `<p style="font-size:12px;color:#334155;margin-bottom:8px;">${escapeHTML(ix.description)}</p>` : ''}
            ${ix.mechanism ? `<div class="card"><h5>Mechanism</h5><p style="font-size:12px;">${escapeHTML(ix.mechanism)}</p></div>` : ''}
            ${ix.management?.length ? `<div class="card"><h5>Management</h5>${ix.management.map((m: any) => `<div class="bullet-item"><strong>${escapeHTML(m.title || m.type || '')}:</strong> ${escapeHTML(m.detail || '')}</div>`).join('')}</div>` : ''}
            ${ix.monitoring?.length ? `<div class="card"><h5>Monitoring</h5>${ix.monitoring.map((m: any) => `<div class="bullet-item"><strong>${escapeHTML(m.test || '')}:</strong> ${escapeHTML(m.detail || '')}</div>`).join('')}</div>` : ''}
            ${ix.alternatives?.length ? `<div class="card"><h5>Alternatives</h5>${ix.alternatives.map((a: any) => `<div class="bullet-item"><strong>${escapeHTML(a.suggestion || '')}:</strong> ${escapeHTML(a.detail || '')}</div>`).join('')}</div>` : ''}
            ${ix.clinical_significance ? `
              <div class="card">
                <h5>Clinical Significance</h5>
                <div style="font-size:12px;">
                  ${ix.clinical_significance.risk_level ? `<div><span style="color:#64748b;">Risk:</span> <strong>${escapeHTML(ix.clinical_significance.risk_level)}</strong></div>` : ''}
                  ${ix.clinical_significance.onset ? `<div><span style="color:#64748b;">Onset:</span> ${escapeHTML(ix.clinical_significance.onset)}</div>` : ''}
                  ${ix.clinical_significance.documentation ? `<div><span style="color:#64748b;">Evidence:</span> ${escapeHTML(ix.clinical_significance.documentation)}</div>` : ''}
                </div>
              </div>` : ''}
          </div>
        </div>`;
    }
  }

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${BASE_STYLES}</style></head><body>
    ${buildHeader('Drug Interaction Report')}
    ${drugsHTML ? `<div style="margin-bottom:16px;">${drugsHTML}</div>` : ''}
    <div class="section-title">Interactions (${interactions.length})</div>
    ${interactionsHTML}
    ${summary ? `<div class="section-title">Clinical Summary</div><p style="font-size:13px;line-height:1.7;">${escapeHTML(summary)}</p>` : ''}
    ${buildDisclaimer('This report is AI-generated and for informational purposes only. Always consult a healthcare professional before making changes to your medications.')}
    ${buildFooter()}
  </body></html>`;

  await generateAndShare(html, `RapidCapsule_Drug_Interactions_${new Date().toISOString().split('T')[0]}`);
}

// ═══════════════════════════════════════════════════════
// Prescription Analysis PDF
// ═══════════════════════════════════════════════════════

export async function generatePrescriptionPDF(data: any): Promise<void> {
  const medications = data?.medications || [];
  const readiness = data?.prescription_readiness;
  const totalCost = data?.total_estimated_cost;

  const statusText = (med: any) => {
    if (!med.in_inventory) return 'Not Available';
    if (med.schedule_class && !['OTC', 'OTC_GENERAL'].includes(med.schedule_class)) return 'Controlled';
    if (!med.in_stock) return 'Out of Stock';
    if (med.requires_prescription) return 'Rx Required';
    return 'In Stock';
  };

  const statusColor = (med: any) => {
    if (!med.in_inventory) return '#94a3b8';
    if (!med.in_stock) return '#ef4444';
    if (med.requires_prescription) return '#f59e0b';
    return '#10b981';
  };

  let medsHTML = medications.map((med: any) => {
    const prices = med.prices || {};
    const priceStr = Object.entries(prices).map(([k, v]: [string, any]) => `${k} ${formatPrice(v)}`).join(' &bull; ');
    return `
      <div style="border:1px solid #e5e7eb;border-radius:10px;padding:12px;margin-bottom:8px;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:4px;">
          <div>
            <strong style="font-size:13px;">${escapeHTML(med.name || med.drug_name || '')}</strong>
            ${med.prescribed_dosage ? `<span style="font-size:11px;color:#64748b;margin-left:6px;">${escapeHTML(med.prescribed_dosage)}</span>` : ''}
          </div>
          <span style="font-size:10px;font-weight:700;color:${statusColor(med)};text-transform:uppercase;">${statusText(med)}</span>
        </div>
        ${med.dosage_form ? `<div style="font-size:11px;color:#64748b;">${escapeHTML(med.dosage_form)}</div>` : ''}
        ${priceStr ? `<div style="font-size:11px;color:#0ea5e9;margin-top:4px;">${priceStr}</div>` : ''}
        ${med.instructions ? `<div style="font-size:11px;color:#334155;margin-top:4px;">${escapeHTML(med.instructions)}</div>` : ''}
      </div>`;
  }).join('');

  let costHTML = '';
  if (totalCost) {
    const entries = Object.entries(totalCost).filter(([, v]) => v);
    if (entries.length) {
      costHTML = `<div class="section-title">Estimated Total Cost</div><div class="card">${entries.map(([k, v]) => `<div style="font-size:13px;margin-bottom:4px;"><strong>${k}:</strong> ${formatPrice(v as number)}</div>`).join('')}</div>`;
    }
  }

  let readinessHTML = '';
  if (readiness) {
    const scoreColor = readiness.score >= 90 ? '#10b981' : readiness.score >= 60 ? '#f59e0b' : '#ef4444';
    readinessHTML = `
      <div class="section-title">Order Readiness</div>
      <div class="card">
        <div style="font-size:18px;font-weight:800;color:${scoreColor};margin-bottom:8px;">${readiness.score}%</div>
        ${readiness.issues?.map((issue: any) => `<div style="font-size:12px;margin-bottom:4px;">${issue.status === 'passed' ? '&#10003;' : '&#10007;'} ${escapeHTML(issue.check)}: ${escapeHTML(issue.message)}</div>`).join('') || ''}
        ${readiness.summary ? `<p style="font-size:12px;color:#334155;margin-top:8px;">${escapeHTML(readiness.summary)}</p>` : ''}
      </div>`;
  }

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${BASE_STYLES}</style></head><body>
    ${buildHeader('Prescription Analysis')}
    ${data.doctor_name ? `<div style="font-size:12px;color:#64748b;margin-bottom:4px;">Prescribed by: <strong>${escapeHTML(data.doctor_name)}</strong></div>` : ''}
    ${data.confidence ? `<div style="font-size:12px;color:#64748b;margin-bottom:16px;">Readability: <strong>${Math.round(data.confidence)}%</strong></div>` : ''}
    <div class="section-title">Medications (${medications.length})</div>
    ${medsHTML}
    ${costHTML}
    ${readinessHTML}
    ${buildDisclaimer('Prices are estimates and may vary. This analysis does not constitute a medical recommendation.')}
    ${buildFooter()}
  </body></html>`;

  await generateAndShare(html, `RapidCapsule_Prescription_${new Date().toISOString().split('T')[0]}`);
}

// ═══════════════════════════════════════════════════════
// Recovery Dashboard PDF
// ═══════════════════════════════════════════════════════

export async function generateRecoveryDashboardPDF(data: any): Promise<void> {
  const riskColors: Record<string, string> = {low: '#10b981', moderate: '#f59e0b', high: '#f97316', critical: '#ef4444'};
  const riskColor = riskColors[data?.risk_level] || '#94a3b8';

  let milestonesHTML = '';
  if (data?.recent_milestones?.length) {
    milestonesHTML = `<div class="section-title">Recent Milestones</div>${data.recent_milestones.map((ms: any) => `
      <div style="display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid #e5e7eb;">
        <span style="font-size:16px;">${ms.icon || '&#127942;'}</span>
        <div style="flex:1;"><strong style="font-size:12px;">${escapeHTML(ms.name)}</strong></div>
        <span style="font-size:11px;color:#0ea5e9;font-weight:600;">+${ms.points} pts</span>
      </div>`).join('')}`;
  }

  let screeningHTML = '';
  if (data?.latest_screening) {
    const s = data.latest_screening;
    const sColor = riskColors[s.risk_level] || '#94a3b8';
    screeningHTML = `<div class="section-title">Latest Screening</div>
      <div class="card">
        <div style="display:flex;justify-content:space-between;align-items:center;">
          <strong>${escapeHTML(s.instrument)}</strong>
          <span style="color:${sColor};font-weight:700;text-transform:capitalize;">${escapeHTML(s.risk_level)}</span>
        </div>
        <div style="font-size:18px;font-weight:800;margin-top:4px;">${s.score} <span style="font-size:12px;color:#64748b;">/ ${s.max_score}</span></div>
      </div>`;
  }

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${BASE_STYLES}</style></head><body>
    ${buildHeader('Recovery Dashboard')}
    <div style="display:flex;gap:16px;margin-bottom:16px;">
      <div style="flex:1;text-align:center;background:#f0fdf4;border-radius:12px;padding:16px;">
        <div style="font-size:36px;font-weight:800;color:#10b981;">${data?.sobriety_days ?? 0}</div>
        <div style="font-size:12px;color:#64748b;font-weight:600;">Days Sober</div>
        ${data?.sobriety_start_date ? `<div style="font-size:10px;color:#94a3b8;">Since ${new Date(data.sobriety_start_date).toLocaleDateString('en-GB', {day: 'numeric', month: 'short', year: 'numeric'})}</div>` : ''}
      </div>
      <div style="flex:1;text-align:center;background:${riskColor}10;border-radius:12px;padding:16px;">
        <div style="font-size:18px;font-weight:700;color:${riskColor};text-transform:capitalize;">${data?.risk_level || 'N/A'}</div>
        <div style="font-size:12px;color:#64748b;font-weight:600;">Risk Level</div>
      </div>
    </div>
    ${data?.primary_substance ? `<div style="font-size:12px;color:#64748b;">Primary substance: <strong>${escapeHTML(data.primary_substance)}</strong></div>` : ''}
    ${data?.today_checked_in != null ? `<div style="margin:12px 0;padding:10px;border-radius:8px;background:${data.today_checked_in ? '#f0fdf4' : '#fef2f2'};font-size:12px;font-weight:600;color:${data.today_checked_in ? '#10b981' : '#ef4444'};">${data.today_checked_in ? 'Daily check-in complete' : 'Check-in pending'}</div>` : ''}
    ${data?.next_milestone ? `
      <div class="section-title">Next Milestone</div>
      <div class="card">
        <strong>${escapeHTML(data.next_milestone.name)}</strong>
        <div style="font-size:11px;color:#64748b;margin:4px 0;">${data.next_milestone.days_remaining} day${data.next_milestone.days_remaining === 1 ? '' : 's'} to go</div>
        <div class="bar-container"><div class="bar-fill" style="width:${Math.min(100, Math.round(((data.next_milestone.days_target - data.next_milestone.days_remaining) / data.next_milestone.days_target) * 100))}%;background:#0ea5e9;"></div></div>
      </div>` : ''}
    ${milestonesHTML}
    ${screeningHTML}
    ${buildDisclaimer('This is a recovery tracking summary, not a clinical report. Share with your care team for professional guidance.')}
    ${buildFooter()}
  </body></html>`;

  await generateAndShare(html, `RapidCapsule_Recovery_${new Date().toISOString().split('T')[0]}`);
}

// ═══════════════════════════════════════════════════════
// Screening Report PDF
// ═══════════════════════════════════════════════════════

export async function generateScreeningReportPDF(data: any): Promise<void> {
  const riskColors: Record<string, string> = {low: '#10b981', mild: '#10b981', moderate: '#f59e0b', moderately_severe: '#f97316', high: '#ef4444', severe: '#ef4444', critical: '#991b1b'};
  const riskColor = riskColors[data?.risk_level] || '#64748b';

  let subscalesHTML = '';
  if (data?.subscale_scores && Object.keys(data.subscale_scores).length) {
    subscalesHTML = `<div class="section-title">Subscale Scores</div>${Object.entries(data.subscale_scores).map(([key, val]) => {
      const pct = Math.min(Number(val) * 10, 100);
      return `<div style="margin-bottom:8px;">
        <div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:3px;">
          <span style="text-transform:capitalize;">${escapeHTML(key.replace(/_/g, ' '))}</span>
          <span style="font-weight:700;">${val}</span>
        </div>
        <div class="bar-container"><div class="bar-fill" style="width:${pct}%;background:${riskColor};"></div></div>
      </div>`;
    }).join('')}`;
  }

  let aiHTML = '';
  if (data?.ai_interpretation) {
    const ai = data.ai_interpretation;
    aiHTML = `<div class="section-title">AI Interpretation</div><div class="card">
      ${ai.summary ? `<p style="font-size:12px;margin-bottom:8px;">${escapeHTML(ai.summary)}</p>` : ''}
      ${ai.risk_assessment ? `<div style="margin-bottom:8px;"><h5 style="font-size:11px;color:#64748b;margin-bottom:4px;">Risk Assessment</h5><p style="font-size:12px;">${escapeHTML(ai.risk_assessment)}</p></div>` : ''}
      ${ai.recommended_interventions?.length ? `<div><h5 style="font-size:11px;color:#64748b;margin-bottom:4px;">Recommended Interventions</h5>${ai.recommended_interventions.map((i: string) => `<div class="bullet-item">${escapeHTML(i)}</div>`).join('')}</div>` : ''}
      ${ai.motivational_message ? `<div style="background:#f0fdf4;border-radius:8px;padding:10px;margin-top:8px;font-size:12px;color:#166534;">${escapeHTML(ai.motivational_message)}</div>` : ''}
    </div>`;
  }

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${BASE_STYLES}</style></head><body>
    ${buildHeader('Screening Report')}
    <div style="text-align:center;margin-bottom:16px;">
      ${data?.instrument_name || data?.instrument ? `<div style="font-size:16px;font-weight:700;margin-bottom:4px;">${escapeHTML(data.instrument_name || data.instrument)}</div>` : ''}
      <div style="font-size:36px;font-weight:800;color:${riskColor};">${data?.total_score ?? 0}</div>
      <div style="font-size:12px;color:#64748b;">out of ${data?.max_score ?? '?'}</div>
      <div style="display:inline-block;background:${riskColor}20;color:${riskColor};font-weight:700;font-size:12px;padding:4px 12px;border-radius:8px;margin-top:8px;text-transform:capitalize;">
        ${escapeHTML((data?.risk_zone_label || data?.risk_level || '').replace(/_/g, ' '))}
      </div>
    </div>
    ${data?.recommendation ? `<p style="font-size:12px;color:#334155;text-align:center;margin-bottom:16px;">${escapeHTML(data.recommendation)}</p>` : ''}
    ${subscalesHTML}
    ${aiHTML}
    ${data?.previous_score != null ? `
      <div class="section-title">Score Change</div>
      <div class="card" style="display:flex;align-items:center;gap:12px;">
        <span style="font-size:12px;color:#64748b;">Previous: ${data.previous_score}</span>
        <span style="font-size:14px;font-weight:700;color:${data.total_score > data.previous_score ? '#ef4444' : data.total_score < data.previous_score ? '#10b981' : '#64748b'};">
          ${data.total_score > data.previous_score ? '&#8593;' : data.total_score < data.previous_score ? '&#8595;' : '='} ${data.total_score > data.previous_score ? '+' : ''}${data.total_score - data.previous_score}
        </span>
        <span style="font-size:12px;">Current: ${data.total_score}</span>
      </div>` : ''}
    ${buildDisclaimer('This is a screening tool, not a clinical diagnosis. Results should be reviewed by a qualified healthcare professional.')}
    ${buildFooter()}
  </body></html>`;

  await generateAndShare(html, `RapidCapsule_Screening_${new Date().toISOString().split('T')[0]}`);
}

// ═══════════════════════════════════════════════════════
// Coping Exercise PDF
// ═══════════════════════════════════════════════════════

export async function generateCopingExercisePDF(data: any): Promise<void> {
  const steps = data?.steps || [];

  let stepsHTML = steps.map((step: string, i: number) => `
    <div style="display:flex;align-items:flex-start;gap:10px;padding:8px 0;border-bottom:1px solid #f1f5f9;">
      <div style="width:24px;height:24px;border-radius:12px;background:#f1f5f9;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
        <span style="font-size:11px;font-weight:700;color:#64748b;">${i + 1}</span>
      </div>
      <p style="font-size:12px;line-height:1.6;flex:1;">${escapeHTML(step)}</p>
    </div>`).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${BASE_STYLES}</style></head><body>
    ${buildHeader('Coping Exercise')}
    <div style="margin-bottom:16px;">
      <div style="font-size:18px;font-weight:700;">${escapeHTML(data?.name || 'Coping Exercise')}</div>
      ${data?.category ? `<span style="display:inline-block;background:#dbeafe;color:#1d4ed8;font-size:11px;font-weight:600;padding:3px 10px;border-radius:6px;margin-top:4px;">${escapeHTML(data.category)}</span>` : ''}
      ${data?.estimated_minutes ? `<span style="font-size:11px;color:#64748b;margin-left:8px;">${data.estimated_minutes} min</span>` : ''}
    </div>
    ${data?.description ? `<p style="font-size:13px;color:#334155;margin-bottom:16px;">${escapeHTML(data.description)}</p>` : ''}
    ${data?.completed ? `<div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;padding:12px;margin-bottom:16px;text-align:center;"><span style="font-weight:700;color:#10b981;">Exercise Completed</span>${data.outcome ? `<p style="font-size:12px;color:#166534;margin-top:4px;">${escapeHTML(data.outcome)}</p>` : ''}</div>` : ''}
    ${steps.length ? `<div class="section-title">Steps</div>${stepsHTML}` : ''}
    ${data?.evidence_base ? `<div class="section-title">Evidence Base</div><p style="font-size:12px;color:#334155;line-height:1.6;">${escapeHTML(data.evidence_base)}</p>` : ''}
    ${buildDisclaimer('This exercise is for informational purposes. It is not a substitute for professional treatment or crisis intervention.')}
    ${buildFooter()}
  </body></html>`;

  await generateAndShare(html, `RapidCapsule_CopingExercise_${new Date().toISOString().split('T')[0]}`);
}

// ═══════════════════════════════════════════════════════
// Risk Assessment PDF
// ═══════════════════════════════════════════════════════

export async function generateRiskAssessmentPDF(data: any): Promise<void> {
  const levelColors: Record<string, string> = {low: '#10b981', moderate: '#f59e0b', high: '#f97316', critical: '#ef4444'};
  const levelLabels: Record<string, string> = {low: 'Low Risk', moderate: 'Moderate Risk', high: 'High Risk', critical: 'Critical Risk'};
  const level = data?.level ?? data?.risk_level ?? 'low';
  const score = data?.score ?? data?.risk_score ?? 0;
  const lColor = levelColors[level] || '#94a3b8';

  const barColor = (s: number) => {
    if (s >= 75) return '#ef4444';
    if (s >= 50) return '#f97316';
    if (s >= 25) return '#f59e0b';
    return '#10b981';
  };

  let categoriesHTML = '';
  if (data?.categories) {
    const cats = Object.entries(data.categories);
    if (cats.length) {
      categoriesHTML = `<div class="section-title">Signal Breakdown</div>${cats.map(([key, cat]: [string, any]) => `
        <div style="margin-bottom:10px;">
          <div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:3px;">
            <span style="text-transform:capitalize;">${escapeHTML(key.replace(/_/g, ' '))}</span>
            <span style="font-weight:700;">${cat.score}/100</span>
          </div>
          <div class="bar-container"><div class="bar-fill" style="width:${cat.score}%;background:${barColor(cat.score)};"></div></div>
          ${cat.weight ? `<div style="font-size:10px;color:#94a3b8;">Weight: ${cat.weight}</div>` : ''}
        </div>`).join('')}`;
    }
  }

  let factorsHTML = '';
  if (data?.top_factors?.length) {
    factorsHTML = `<div class="section-title">Top Contributing Factors</div>${data.top_factors.slice(0, 5).map((f: any) => `
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">
        <div style="flex:1;font-size:12px;">${escapeHTML(f.name || f.signal || f.label || '')}</div>
        <span style="background:#fef2f2;color:#ef4444;font-size:10px;font-weight:700;padding:2px 8px;border-radius:6px;">+${f.contribution || f.value || 0}</span>
      </div>`).join('')}`;
  }

  let suggestionsHTML = '';
  if (data?.suggestions?.length) {
    suggestionsHTML = `<div class="section-title">Suggested Actions</div>${data.suggestions.map((s: any) => `<div class="bullet-item">${escapeHTML(s.text || s)}</div>`).join('')}`;
  }

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${BASE_STYLES}</style></head><body>
    ${buildHeader('Risk Assessment Report')}
    <div style="text-align:center;margin-bottom:20px;">
      <div style="font-size:48px;font-weight:800;color:${lColor};">${score}</div>
      <div style="font-size:14px;color:#64748b;">/ 100</div>
      <div style="display:inline-block;background:${lColor}20;color:${lColor};font-weight:700;font-size:13px;padding:4px 14px;border-radius:8px;margin-top:8px;">
        ${escapeHTML(levelLabels[level] || capitalize(level))}
      </div>
    </div>
    ${categoriesHTML}
    ${factorsHTML}
    ${suggestionsHTML}
    ${buildDisclaimer('This risk assessment is an AI-generated estimate, not a clinical diagnosis. Always consult your care team for professional guidance.')}
    ${buildFooter()}
  </body></html>`;

  await generateAndShare(html, `RapidCapsule_RiskAssessment_${new Date().toISOString().split('T')[0]}`);
}
